// Generated by gencpp from file rover_computer/angle_to_rotRequest.msg
// DO NOT EDIT!


#ifndef ROVER_COMPUTER_MESSAGE_ANGLE_TO_ROTREQUEST_H
#define ROVER_COMPUTER_MESSAGE_ANGLE_TO_ROTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace rover_computer
{
template <class ContainerAllocator>
struct angle_to_rotRequest_
{
  typedef angle_to_rotRequest_<ContainerAllocator> Type;

  angle_to_rotRequest_()
    : vec()  {
    }
  angle_to_rotRequest_(const ContainerAllocator& _alloc)
    : vec(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _vec_type;
  _vec_type vec;





  typedef boost::shared_ptr< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct angle_to_rotRequest_

typedef ::rover_computer::angle_to_rotRequest_<std::allocator<void> > angle_to_rotRequest;

typedef boost::shared_ptr< ::rover_computer::angle_to_rotRequest > angle_to_rotRequestPtr;
typedef boost::shared_ptr< ::rover_computer::angle_to_rotRequest const> angle_to_rotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_computer::angle_to_rotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover_computer::angle_to_rotRequest_<ContainerAllocator1> & lhs, const ::rover_computer::angle_to_rotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vec == rhs.vec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover_computer::angle_to_rotRequest_<ContainerAllocator1> & lhs, const ::rover_computer::angle_to_rotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover_computer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5466fc697deeda647d8a50c8f0a1b4ad";
  }

  static const char* value(const ::rover_computer::angle_to_rotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5466fc697deeda64ULL;
  static const uint64_t static_value2 = 0x7d8a50c8f0a1b4adULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_computer/angle_to_rotRequest";
  }

  static const char* value(const ::rover_computer::angle_to_rotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 vec\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rover_computer::angle_to_rotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angle_to_rotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_computer::angle_to_rotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_computer::angle_to_rotRequest_<ContainerAllocator>& v)
  {
    s << indent << "vec: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.vec);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_COMPUTER_MESSAGE_ANGLE_TO_ROTREQUEST_H
